# Generated by Django 6.0.2 on 2026-02-20 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(choices=[('CLARA', 'Professional Clara'), ('MAYA', 'Student Maya')], max_length=10)),
                ('goal', models.CharField(choices=[('FAMILY', 'Family Fund'), ('CAREER', 'Career Break'), ('WEALTH', 'Wealth Building')], max_length=10)),
                ('xp', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
