# Generated by Django 6.0.2 on 2026-02-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(choices=[('FAMILY FUND', 'Family Fund'), ('CAREER BREAK', 'Career Break'), ('WEALTH BUILDING', 'Wealth Building')], max_length=100),
        ),
    ]
